name: Trigger auto deployment for container-app-yujkk6jsxxygi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-yujkk6jsxxygi-AutoDeployTrigger-399b7500-25a8-4ce7-a2f2-f876286c2988.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPYUJKK6JSXXYGI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPYUJKK6JSXXYGI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPYUJKK6JSXXYGI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPYUJKK6JSXXYGI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPYUJKK6JSXXYGI_REGISTRY_PASSWORD }}
          containerAppName: container-app-yujkk6jsxxygi
          resourceGroup: todonodejspgsqlgoogleauthb83ea012
          imageToBuild: default/container-app-yujkk6jsxxygi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


